apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - containerPort: 3000
        env:
        # Admin settings
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        
        # Anonymous access
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_NAME
          value: "Main Org."
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        
        # Security for embedding
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_SECURITY_COOKIE_SAMESITE
          value: "disabled"
        - name: GF_SECURITY_COOKIE_SECURE
          value: "false"
        
        # Disable login for anonymous users
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        
        # Default permissions
        - name: GF_USERS_DEFAULT_PERMISSIONS
          value: "Viewer"
        - name: GF_RBAC_PERMISSION_CACHE_ENABLED
          value: "false"
        
        # Datasource permissions
        - name: GF_DATASOURCES_DEFAULT_ACCESS_MODE
          value: "proxy"
        - name: GF_DATASOURCES_DEFAULT_EDITABLE
          value: "false"
        
        # Public dashboards
        - name: GF_PUBLIC_DASHBOARDS_ENABLED
          value: "true"
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "publicDashboards"
        
        # Allow datasource access for public dashboards
        - name: GF_DATASOURCES_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: "true"
        - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: "influxdb"
        
        volumeMounts:
        - name: grafana-ini
          mountPath: /etc/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: eagle-dashboard
          mountPath: /var/lib/grafana/dashboards/eagle
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: grafana-ini
        configMap:
          name: grafana-ini
      - name: datasources
        configMap:
          name: grafana-datasources-public-v2
      - name: dashboards-provider
        configMap:
          name: grafana-dashboards-public
      - name: dashboards
        configMap:
          name: grafana-dashboard-power
      - name: eagle-dashboard
        configMap:
          name: grafana-dashboard-permissions