FROM grafana/grafana:10.2.0

# Copy provisioning files  
COPY provisioning /etc/grafana/provisioning

# Copy custom configuration (will be overridden by env vars)
COPY grafana.ini /etc/grafana/grafana.ini