app = "linknode-grafana"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  GF_SECURITY_ALLOW_EMBEDDING = "true"
  GF_AUTH_ANONYMOUS_ENABLED = "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE = "Viewer"
  GF_AUTH_DISABLE_LOGIN_FORM = "true"
  GF_LOG_LEVEL = "info"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "5s"
    interval = "15s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "grafana_data"
  destination = "/var/lib/grafana"