apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-public-v2
  namespace: demo-app
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: InfluxDB
      uid: influxdb
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      isDefault: true
      editable: false
      basicAuth: false
      withCredentials: false
      jsonData:
        version: Flux
        organization: rackspace
        defaultBucket: power_metrics
        tlsSkipVerify: true
      secureJsonData:
        token: my-super-secret-auth-token
    deleteDatasources: []