apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
data:
  ENVIRONMENT: "production"
  FEATURE_FLAG: "enabled"
  APP_VERSION: "1.0.0"
  DATABASE_URL: "postgresql://demo:demo@postgres:5432/demodb"