apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: demo-app
data:
  grafana.ini: |
    [server]
    root_url = http://119.9.118.22:30300
    enable_gzip = true

    [security]
    allow_embedding = true
    cookie_secure = false
    cookie_samesite = disabled
    content_security_policy = false
    content_security_policy_template = ""
    disable_gravatar = true
    
    [auth]
    disable_login_form = false
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    hide_version = false
    
    [auth.basic]
    enabled = true
    
    [rbac]
    permission_cache = false

    [users]
    allow_sign_up = false
    allow_org_create = false
    
    [dataproxy]
    timeout = 30
    keep_alive_seconds = 30
    
    [panels]
    disable_sanitize_html = true
    
    [public_dashboards]
    enabled = true
    
    [feature_toggles]
    enable = publicDashboards