apiVersion: v1
kind: Service
metadata:
  name: eagle-xml-monitor
  namespace: demo-app
  labels:
    app: eagle-xml-monitor
spec:
  type: NodePort
  selector:
    app: eagle-xml-monitor
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
    name: http