app = "linknode-influxdb"
primary_region = "ord"

[build]

[env]
  DOCKER_INFLUXDB_INIT_MODE = "setup"
  DOCKER_INFLUXDB_INIT_ORG = "linknode"
  DOCKER_INFLUXDB_INIT_BUCKET = "energy"
  DOCKER_INFLUXDB_INIT_RETENTION = "30d"
  # IMPORTANT: Set these as fly secrets:
  # fly secrets set DOCKER_INFLUXDB_INIT_USERNAME=admin
  # fly secrets set DOCKER_INFLUXDB_INIT_PASSWORD=your-secure-password
  # fly secrets set DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-secure-token

[[services]]
  internal_port = 8086
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = false
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "influxdb_data"
  destination = "/var/lib/influxdb2"