app = "linknode-influxdb"
primary_region = "ord"

[build]

[env]
  DOCKER_INFLUXDB_INIT_MODE = "setup"
  DOCKER_INFLUXDB_INIT_USERNAME = "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD = "admin123456"
  DOCKER_INFLUXDB_INIT_ORG = "linknode"
  DOCKER_INFLUXDB_INIT_BUCKET = "energy"
  DOCKER_INFLUXDB_INIT_RETENTION = "30d"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN = "my-super-secret-auth-token"

[[services]]
  internal_port = 8086
  protocol = "tcp"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "influxdb_data"
  destination = "/var/lib/influxdb2"