apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://linknode-influxdb.internal:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: linknode
      defaultBucket: energy
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: false