name: Test Queue Monitor

on:
  workflow_dispatch:
    inputs:
      delay:
        description: 'Artificial delay in seconds'
        required: false
        default: '5'
        type: string

concurrency:
  group: test-queue-${{ github.ref }}
  cancel-in-progress: true

jobs:
  queue-monitor:
    name: Queue Time Monitor
    uses: ./.github/workflows/includes/queue-monitor.yml
    
  test-job:
    name: Test Job with Queue Monitor
    runs-on: ubuntu-latest
    needs: [queue-monitor]
    timeout-minutes: 5
    steps:
      - name: Log timestamps
        run: |
          echo "🕐 Workflow Timing Information:"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Created At: ${{ github.run_created_at }}"
          echo "Started At: ${{ github.run_started_at }}"
          
      - name: Artificial delay
        run: |
          DELAY="${{ github.event.inputs.delay || '5' }}"
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY
          
      - name: Success
        run: echo "✅ Test completed successfully!"