#!/bin/bash

echo "🚀 Quick Cloudflare Worker Fix"
echo "=============================="
echo ""
echo "Since the monitoring service is now deployed and working at:"
echo "http://119.9.118.22:30500/api/power-data"
echo ""
echo "You have THREE working options for your EAGLE device:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Direct HTTP (WORKING NOW!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Protocol: HTTP"
echo "Hostname: 119.9.118.22"
echo "URL: /api/power-data"
echo "Port: 30500"
echo "Format: JSON"
echo ""
echo "✅ This is the easiest option - no Cloudflare update needed!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: Manual Cloudflare Update"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Click on linknode.com"
echo "3. Go to Workers Routes (left sidebar)"
echo "4. Click on your worker"
echo "5. Click 'Quick Edit'"
echo "6. Select ALL the code and delete it"
echo "7. Copy ALL the code from the file below and paste it:"
echo ""
echo "File location: $(pwd)/worker.js"
echo ""
echo "8. Click 'Save and Deploy'"
echo ""
echo "Then configure EAGLE with:"
echo "Protocol: HTTPS"
echo "Hostname: linknode.com"
echo "URL: /api/power-data"
echo "Port: 443"
echo "Format: JSON"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Test Now"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test if everything is working:"
echo ""
echo "curl http://119.9.118.22:30500/api/power-data/test"
echo ""
echo "Send test data:"
echo "curl -X POST http://119.9.118.22:30500/api/power-data \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"DeviceMacId\":\"test\",\"Demand\":3500,\"Multiplier\":1,\"Divisor\":1000}'"
echo ""
echo "View Grafana Dashboard:"
echo "http://119.9.118.22:30300 (login: admin/admin)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"